image: docker:stable

services:
  - docker:dind

variables:
  CONTAINER_IMAGE: gitlab.bongobd.com:4567/$CI_PROJECT_PATH
  DOCKER_HOST: gitlab.bongobd.com:4567
  DOCKER_DRIVER: overlay2

before_script:
  - echo "$CI_JOB_TOKEN" | docker login $DOCKER_HOST -u gitlab-ci-token --password-stdin

build:
  stage: build
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:latest