image: docker:stable

services:
  - docker:dind
  
variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN

build:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
    
test:
  stage: test
  script:
    - docker run --name pg-con-$CI_JOB_ID -d -e POSTGRES_PASSWORD=password --rm postgres:9.6
    - docker run $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA ./lint.sh
    - docker exec pg-con createdb -U postgres ms-auth-test
    - docker run -e DATABASE_URL='postgresql://postgres:password@postgres:5432/ms-auth' --link pg-con-$CI_JOB_ID:postgres $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA ./test.sh
  after_script:  
    - docker stop pg-con-$CI_JOB_ID
