"""empty message

Revision ID: 1ed662a79b3a
Revises: 4c54ea1eed4b
Create Date: 2019-04-07 15:17:30.077895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed662a79b3a'
down_revision = '4c54ea1eed4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('user_role', sa.Column('updated_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role', 'updated_by')
    op.drop_column('user_role', 'created_by')
    # ### end Alembic commands ###
