"""empty message

Revision ID: 33980f19865e
Revises: 1e889076ad7c
Create Date: 2019-04-11 14:37:19.764263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33980f19865e'
down_revision = '1e889076ad7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_codes',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('types', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.alter_column('user_role', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_role', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('users', sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.drop_constraint('users_updated_by_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['updated_by'], ['id'])
    op.drop_column('users', 'verification_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code', sa.VARCHAR(length=130), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_updated_by_fkey', 'users', 'users', ['updated_by'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'verified')
    op.drop_column('users', 'created_by')
    op.alter_column('user_role', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_role', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('verification_codes')
    # ### end Alembic commands ###
